# Generated by Django 3.2.13 on 2022-10-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coinsSupportedCoinListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('coin_slug', models.CharField(max_length=100, unique=True)),
                ('thumb', models.CharField(max_length=300, unique=True)),
                ('small', models.CharField(max_length=300, unique=True)),
                ('large', models.CharField(max_length=300, unique=True)),
                ('is_supported', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
